version: '3.7'

services:

  backend:
    build: ./app
    image: ${REGISTRY_HOST}:${REGISTRY_PORT}/nirax/nirax_transceiver:latest
    container_name: nirax_transceiver
    env_file:
      - ./app/.env
      - ./.env
    ports:
      - ${SERVER_PORT}:8000
    volumes:
      - ./app/logs:/app/logs
    restart: always
