version: '3.7'

services:

  backend:
    build: ./app
    container_name: nirax_transceiver
    env_file:
      - ./app/.env
    ports:
      - ${SERVER_PORT}:8000
    volumes:
      - ./app/logs:/app/logs
    restart: on-failure
