name: transceiver-dev
env:
  PROJECT_NAME: "nirax_transceiver"
  STACK: "transceiver"
  STAGE: "prod"
  BRANCH: "main"
  #  VERSION: "latest"
  VERSION: ${{ github.sha }}
  WORKDIR: "transceiver"
  REPOSITORY: "nirax"
  INFRA_WORKDIR: "/home/nirax/infra/nirax_infra/nirax_transceiver"

on:
  push:
    branches: [ deskent ]

jobs:
  send_message:
    name: Send message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send message using curl
        env:
          MESSAGE: "[${{ env.PROJECT_NAME}}]: Branch: ${{ env.BRANCH }}
            \n${{ github.actor }} created commit with message:
            \n${{ github.event.commits[0].message }}
            \n\n${{ github.event.pull_request.body }}

            \n\nRepository: ${{ github.repository }}
            \nSee changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            "
        run: |
          curl \
          -X POST \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": ${{ secrets.TELEGRAM_CHAT_ID }}, "text": "${{ env.MESSAGE }}", "disable_notification": true}' \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage

  tests_backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10" ]

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: 'test'
          MONGO_INITDB_ROOT_PASSWORD: 'test'
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f ${{ env.WORKDIR }}/requirements.txt ]; then pip install -r ${{ env.WORKDIR }}/requirements.txt; fi

      - name: Test with pytest
        run: |
          export CARETTA_API_KEY=${{secrets.CARETTA_API_KEY}}
          cd ${{ env.WORKDIR }} \
          && python -m pytest -rf --maxfail=4 -k "github" ./tests

      - name: Telegram notification on Failure
        if: failure()
        env:
          MESSAGE: "
          TESTS: FAILED!!!
          \n[${{ env.PROJECT_NAME}}]: Branch ${{ env.BRANCH }}:
          \nPython version ${{ matrix.python-version }}
          \nVersion: ${{ env.VERSION}}
          "
        run: |
          curl \
          -X POST \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": ${{ secrets.TELEGRAM_CHAT_ID }}, "text": "${{ env.MESSAGE }}", "disable_notification": false}' \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage

      - name: Push to registry message
        env:
          MESSAGE: "
          TESTS: OK
          \n[${{ env.PROJECT_NAME}}]: Branch: ${{ env.BRANCH }}
          \nPython version ${{ matrix.python-version }}
          \nVersion: ${{ env.VERSION}}
          "
        run: |
          curl \
          -X POST \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": ${{ secrets.TELEGRAM_CHAT_ID }}, "text": "${{ env.MESSAGE }}", "disable_notification": true}' \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage

  building:
    name: Build and push containers
    runs-on: ubuntu-latest
    needs: [ tests_backend ]
    steps:
      - uses: actions/checkout@v3
      - name: Push to registry
        run: |
          echo '{"insecure-registries": ["${{ secrets.REGISTRY_SERVER }}"]}' >> daemon.json && sudo cp daemon.json /etc/docker/ \
          && sudo systemctl restart docker \
          && cd ${{ env.WORKDIR }} \
          && docker build -t ${{ env.PROJECT_NAME }}:${{ env.VERSION}} .

          docker image tag \
          ${{ env.PROJECT_NAME }}:${{ env.VERSION}} \
          ${{ secrets.REGISTRY_SERVER }}/${{ env.REPOSITORY }}/${{ env.PROJECT_NAME }}:${{ env.VERSION}}

          docker push \
          ${{ secrets.REGISTRY_SERVER }}/${{ env.REPOSITORY }}/${{ env.PROJECT_NAME }}:${{ env.VERSION}}

      - name: Telegram notification on Failure
        if: failure()
        env:
          MESSAGE: "
          Building: FAILED!!!
          \n[${{ env.PROJECT_NAME}}]: Branch ${{ env.BRANCH }}:
          \nPython version ${{ matrix.python-version }}
          \nVersion: ${{ env.VERSION}}
          "
        run: |
          curl \
          -X POST \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": ${{ secrets.TELEGRAM_CHAT_ID }}, "text": "${{ env.MESSAGE }}", "disable_notification": false}' \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage

      - name: Push to registry message
        env:
          MESSAGE: "
          Building: OK
          \n[${{ env.PROJECT_NAME}}]: Branch: ${{ env.BRANCH }}
          \nPython version ${{ matrix.python-version }}
          \nVersion: ${{ env.VERSION}}
          "
        run: |
          curl \
          -X POST \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": ${{ secrets.TELEGRAM_CHAT_ID }}, "text": "${{ env.MESSAGE }}", "disable_notification": true}' \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage

  deploy:
    name: Deploy and report
    runs-on: ubuntu-latest
    #    needs: [ building ]
    steps:
      - name: Deploy code to remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_PROD_NEW }}
          username: ${{ secrets.USERNAME_PROD }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD_NEW }}
          port: 22
          script: |
            cd ${{ env.INFRA_WORKDIR }}
            git pull
            source ./update_backend.sh ${{ env.VERSION }}

      - uses: actions/checkout@v3
      - name: Telegram notification on Failure
        if: failure()
        env:
          MESSAGE: "
          Deploy: FAILED!!!
          \n[${{ env.PROJECT_NAME}}]: Branch ${{ env.BRANCH }}:
          \nVersion: ${{ env.VERSION}}
          "
        run: |
          curl \
          -X POST \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": ${{ secrets.TELEGRAM_CHAT_ID }}, "text": "${{ env.MESSAGE }}", "disable_notification": false}' \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage

      - name: Send notification on Success
        env:
          MESSAGE: "
          Deploy: OK
          \n[${{ env.PROJECT_NAME}}]: Branch ${{ env.BRANCH }}:
          \nVersion: ${{ env.VERSION}}
          "
        run: |
          curl \
          -X POST \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": ${{ secrets.TELEGRAM_CHAT_ID }}, "text": "${{ env.MESSAGE }}", "disable_notification": true}' \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage
